[versions]
annotations = "24.0.1"
junit = "5.9.3"
javafx = "20.0.2"
log4j = "2.20.0"
gson = "2.10.1"

[libraries]
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

[bundles]
log4j = ["log4j-api", "log4j-core"]

[plugins]
licenser = { id = "org.cadixdev.licenser", version = "0.6.1" }
javafx = { id = "org.openjfx.javafxplugin", version = "0.0.14" }
